MedicalAppointmentsManagement/Controllers/AdminsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MedicalAppointmentsManagement.Models;

namespace MedicalAppointmentsManagement.Controllers
{
    public class AdminsController : Controller
    {
        private MedicalDBEntities db = new MedicalDBEntities();

        // Login
        // GET: Admins/Index -> redirect to login
        public ActionResult Index()
        {
            return RedirectToAction("Login");
        }

        // Login
        // GET: Admins/Login
        public ActionResult Login()
        {
            return View();
        }

        // POST: Admins/Login
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(ADMIN objUser)
        {

            using (MedicalDBEntities db = new MedicalDBEntities())
            {
                var obj = db.ADMINs.Where(a => a.username.Equals(objUser.username) && a.password.Equals(objUser.password)).FirstOrDefault();
                if (obj != null)
                {
                    Session["admin"] = obj.userid.ToString();
                    Session["UserName"] = obj.username.ToString();
                    return RedirectToAction("Menu");
                }
            }
            ViewData["Error"] = "Error";
            return View(objUser);
        }

        // GET: Admins/Menu
        public ActionResult Menu()
        {
            if (Session["admin"] != null)
            {
                return View();

            }
            else
            {
                return RedirectToAction("Login");
            }
        }

        // Admins/Logout
        public ActionResult Logout()
        {
            Session["admin"] = null;
            Session["UserName"] = null;
            Session.Abandon();
            return Redirect("../Home");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MedicalAppointmentsManagement/Views/Admins/Create.cshtml
@model MedicalAppointmentsManagement.Models.ADMIN

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ADMIN</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.userid, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.userid, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.userid, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.username, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.username, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.username, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MedicalAppointmentsManagement/Views/Admins/Delete.cshtml
@model MedicalAppointmentsManagement.Models.ADMIN

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ADMIN</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.username)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.username)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.password)
        </dd>


    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MedicalAppointmentsManagement/Views/Admins/Details.cshtml
@model MedicalAppointmentsManagement.Models.ADMIN

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>ADMIN</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.username)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.username)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.password)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.userid }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MedicalAppointmentsManagement/Views/Admins/Edit.cshtml
@model MedicalAppointmentsManagement.Models.ADMIN

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ADMIN</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.userid)

        <div class="form-group">
            @Html.LabelFor(model => model.username, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.username, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.username, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MedicalAppointmentsManagement/Views/Admins/Index.cshtml
@model IEnumerable<MedicalAppointmentsManagement.Models.ADMIN>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.username)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.password)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.username)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.password)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.userid }) |
            @Html.ActionLink("Details", "Details", new { id=item.userid }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.userid })
        </td>
    </tr>
}

</table>

MedicalAppointmentsManagement/Views/Admins/Login.cshtml
@model MedicalAppointmentsManagement.Models.ADMIN

@{
    ViewBag.Title = "Login";
}

@* Label *@
<div class="row">
    <div class="col-md-5 col-7 col-xl-4 mx-auto">
        <h1 class="display-5">Login</h1>
    </div>
</div>

@using (Html.BeginForm("Login", "Admins", FormMethod.Post))
{
    @* Login *@
    <div class="row">
        <div class="col-md-5 col-7 col-xl-4 mx-auto">
            <div class="border border-dark bg-dark rounded p-2">
                <h1 class="display-6 pb-1">
                    Admin
                </h1>
                @if (ViewData["Error"] != null)
                {
                    @Html.Partial("_StatusMessages")
                }
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)
                    <div class="mb-3">
                        @Html.LabelFor(model => model.username, htmlAttributes: new {@class = "form-label"})
                        @Html.EditorFor(model => model.username, new {htmlAttributes = new {@class = "form-control"}})
                        @Html.ValidationMessageFor(model => model.username, "", new {@class = "text-danger"})
                    </div>
                    <div class="mb-3">
                        @Html.LabelFor(model => model.password, htmlAttributes: new {@class = "form-label"})
                        @Html.EditorFor(model => model.password, new {htmlAttributes = new {@class = "form-control",  type = "password"  }})
                        @Html.ValidationMessageFor(model => model.password, "", new {@class = "text-danger"})

                    </div>
                    <button type="submit" class="btn btn-outline-primary">Login</button>
            </div>
        </div>
    </div><br>
}

MedicalAppointmentsManagement/Views/Admins/Menu.cshtml
@{
    ViewBag.Title = "Menu";
}

<div class="row">
    <div class="col-lg-6 mx-auto">
        <h1 class="display-5">Menu</h1>
    </div>
</div>

<div class="row">
    <div class="col-lg-6 mx-auto">
        <div class="border border-dark bg-dark rounded p-2">
            <p class="lead">Welcome @Session["UserName"].ToString()! How are you today?</p>
        </div>
    </div>
</div><br>

<div class="row">
    <div class="col-lg-6 mx-auto">
        <div class="border border-dark bg-dark rounded p-2">
            <h1 class="display-6 pb-1">Appointment</h1>
            <p class="lead">Create an appointment</p>
            <a href="../Appointments/Create" type="button" class="btn btn-outline-primary">Create</a>
            <p class="lead pt-2">View appointmens</p>
            <a href="../Appointments" type="button" class="btn btn-outline-primary">View</a>
        </div>
    </div>
</div><br>