MedicalAppointmentsManagement/Models/DOCTOR.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalAppointmentsManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCTOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DOCTOR()
        {
            this.APPOINTMENTs = new HashSet<APPOINTMENT>();
        }
    
        public int doctorAMKA { get; set; }
        public string username { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string specialty { get; set; }
        public string password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APPOINTMENT> APPOINTMENTs { get; set; }
    }
}

MedicalAppointmentsManagement/Controllers/DoctorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MedicalAppointmentsManagement.Models;

namespace MedicalAppointmentsManagement.Controllers
{
    public class DoctorsController : Controller
    {
        private MedicalDBEntities db = new MedicalDBEntities();


        // Login
        // GET: Doctors/Login
        public ActionResult Login()
        {
            return View();
        }

        // POST: Doctors/Login
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(DOCTOR objUser)
        {

            using (MedicalDBEntities db = new MedicalDBEntities())
            {
                var obj = db.DOCTORs.Where(a => a.username.Equals(objUser.username) && a.password.Equals(objUser.password)).FirstOrDefault();
                if (obj != null)
                {
                    Session["doctorAMKA"] = obj.doctorAMKA.ToString();
                    Session["UserName"] = obj.username.ToString();
                    return RedirectToAction("Menu");
                }
            }
            ViewData["Error"] = "Error";
            return View(objUser);
        }

        // GET: Doctors/Menu
        public ActionResult Menu()
        {
            if (Session["doctorAMKA"] == null)
            {
                return RedirectToAction("Login");
            }
            return View();
        }

        //Logout
        public ActionResult Logout()
        {
            Session["doctorAMKA"] = null;
            Session["UserName"] = null;
            Session.Abandon();
            return Redirect("../Home");
        }


        // GET: Index -> login
        public ActionResult Index()
        {
            return RedirectToAction("Menu");
        }


        // GET: Doctors/Details/5
        public ActionResult Details(int? id)
        {
            if (Session["doctorAMKA"] == null)
            {
                return RedirectToAction("Login");
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DOCTOR dOCTOR = db.DOCTORs.Find(id);
            if (dOCTOR == null)
            {
                return HttpNotFound();
            }
            return View(dOCTOR);
        }

        // GET: Doctors/Edit/5
        public ActionResult Edit(int? id)
        {
            if (Session["doctorAMKA"] == null || !Session["doctorAMKA"].ToString().Equals(id.ToString()))
            {
                return RedirectToAction("Login");
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DOCTOR dOCTOR = db.DOCTORs.Find(id);
            if (dOCTOR == null)
            {
                return HttpNotFound();
            }
            return View(dOCTOR);
        }

        // POST: Doctors/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "doctorAMKA,username,name,surname,specialty,password")] DOCTOR doctor)
        {
            if (Session["doctorAMKA"] == null || !Session["doctorAMKA"].ToString().Equals(doctor.doctorAMKA.ToString()))
            {
                return RedirectToAction("Login");
            }

            if (ModelState.IsValid)
            {
                db.Entry(doctor).State = EntityState.Modified;
                db.SaveChanges();
                return Redirect("~/Doctors/Details/"+doctor.doctorAMKA);
            }
            return View(doctor);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MedicalAppointmentsManagement/Views/Doctors/Create.cshtml
@model MedicalAppointmentsManagement.Models.DOCTOR

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>DOCTOR</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.doctorAMKA, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.doctorAMKA, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.doctorAMKA, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.username, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.username, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.username, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.surname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.surname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.surname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.specialty, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.specialty, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.specialty, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MedicalAppointmentsManagement/Views/Doctors/Delete.cshtml
@model MedicalAppointmentsManagement.Models.DOCTOR

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>DOCTOR</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.username)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.username)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.surname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.surname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.specialty)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.specialty)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.password)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MedicalAppointmentsManagement/Views/Doctors/Details.cshtml
@model MedicalAppointmentsManagement.Models.DOCTOR

@{
    ViewBag.Title = "Details";
}

@* Label *@
<div class="row">
    <div class="col-lg-8 mx-auto">
        <h1 class="display-5">Profile</h1>
    </div>
</div>


@* Details *@
<div class="row">
    <div class="col-lg-8 mx-auto">
        <div class="border border-dark bg-dark rounded p-2">
            <h1 class="display-6 pb-1">
                @Html.DisplayFor(model => model.username) Profile details.
            </h1>
            <dl class="dl-horizontal">

                <dt>
                    @Html.DisplayNameFor(model => model.username)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.username)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.name)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.name)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.surname)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.surname)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.specialty)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.specialty)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.password)
                </dt>

                <dd>
                    *******
                </dd>
            </dl>
            <a href="../Edit/@Model.doctorAMKA" class="btn btn-outline-primary" role="button">Edit</a><br />
            @Html.ActionLink("Back", "../Doctors/Menu")
        </div>
    </div>
</div>

MedicalAppointmentsManagement/Views/Doctors/Edit.cshtml
@model MedicalAppointmentsManagement.Models.DOCTOR

@{
    ViewBag.Title = "Edit";
}


@* Label *@
<div class="row">
    <div class="col-md-6 col-9 col-xl-4 mx-auto">
        <h1 class="display-5">Edit</h1>
    </div>
</div>


@using (Html.BeginForm())
{
    @* Create *@
    <div class="row">
        <div class="col-md-6 col-9 col-xl-4 mx-auto">
            <div class="border border-dark bg-dark rounded p-2">
                <h1 class="display-6 pb-1">
                    @Model.username Profile
                </h1>
                @if (ViewData["Error"] != null)
                {
                    @Html.Partial("_StatusMessages")
                }
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.doctorAMKA)
                    @Html.HiddenFor(model => model.specialty)
                    <div class="mb-3">
                        @Html.LabelFor(model => model.username, htmlAttributes: new { @class = "form-label" })
                        @Html.EditorFor(model => model.username, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.username, "", new { @class = "text-danger" })
                    </div>
                    <div class="mb-3">
                        @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "form-label" })
                        @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
                    </div>

                    <div class="mb-3">
                        @Html.LabelFor(model => model.surname, htmlAttributes: new { @class = "form-label" })
                        @Html.EditorFor(model => model.surname, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.surname, "", new { @class = "text-danger" })
                    </div>

                    <div class="mb-3">
                        @Html.LabelFor(model => model.password, htmlAttributes: new { @class = "form-label" })
                        @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control" }})
                        @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <button type="submit" class="btn btn-outline-primary">Save</button><br />
                            <a href="../Details/@Model.doctorAMKA">Cancel</a><br />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div><br>
}

MedicalAppointmentsManagement/Views/Doctors/Index.cshtml
@model IEnumerable<MedicalAppointmentsManagement.Models.DOCTOR>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.username)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.surname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.specialty)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.password)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.username)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.surname)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.specialty)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.password)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.doctorAMKA }) |
            @Html.ActionLink("Details", "Details", new { id=item.doctorAMKA }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.doctorAMKA })
        </td>
    </tr>
}

</table>

MedicalAppointmentsManagement/Views/Doctors/Login.cshtml
@model MedicalAppointmentsManagement.Models.DOCTOR

@{
    ViewBag.Title = "Login";
}

@* Label *@
<div class="row">
    <div class="col-md-5 col-7 col-xl-4 mx-auto">
        <h1 class="display-5">Login</h1>
    </div>
</div>


@using (Html.BeginForm("Login", "Doctors", FormMethod.Post))
{
 @* Login *@
    <div class="row">
        <div class="col-md-5 col-7 col-xl-4 mx-auto">
            <div class="border border-dark bg-dark rounded p-2">
                <h1 class="display-6 pb-1">
                    Doctor
                </h1>
                @if (ViewData["Error"] != null)
                {
                    @Html.Partial("_StatusMessages")
                }
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)
                    <div class="mb-3">
                        @Html.LabelFor(model => model.username, htmlAttributes: new {@class = "form-label"})
                        @Html.EditorFor(model => model.username, new {htmlAttributes = new {@class = "form-control"}})
                        @Html.ValidationMessageFor(model => model.username, "", new {@class = "text-danger"})
                        <div id="emailHelp" class="form-text">We'll never share your credentials with anyone else.</div>
                    </div>
                    <div class="mb-3">
                        @Html.LabelFor(model => model.password, htmlAttributes: new {@class = "form-label"})
                        @Html.EditorFor(model => model.password, new {htmlAttributes = new {@class = "form-control",  type = "password"  }})
                        @Html.ValidationMessageFor(model => model.password, "", new {@class = "text-danger"})

                    </div>
                    <button type="submit" class="btn btn-outline-primary">Login</button>
            </div>
        </div>
    </div><br>

}

MedicalAppointmentsManagement/Views/Doctors/Menu.cshtml
@{
    ViewBag.Title = "Menu";
}

<div class="row">
    <div class="col-lg-6 mx-auto">
        <h1 class="display-5">Menu</h1>
    </div>
</div>

<div class="row">
    <div class="col-lg-6 mx-auto">
        <div class="border border-dark bg-dark rounded p-2">
            <p class="lead">Welcome @Session["UserName"].ToString()! How are you today?</p>
        </div>
    </div>
</div><br>

<div class="row">
    <div class="col-lg-6 mx-auto">
        <div class="border border-dark bg-dark rounded p-2">
            <h1 class="display-6 pb-1">Appointment</h1>
            <p class="lead">Create an appointment</p>
            <a href="../Appointments/Create" type="button" class="btn btn-outline-primary">Create</a>
            <p class="lead pt-2">View appointmens</p>
            <a href="../Appointments" type="button" class="btn btn-outline-primary">View</a>
        </div>
    </div>
</div><br>

<div class="row">
    <div class="col-lg-6 mx-auto">
        <div class="border border-dark bg-dark rounded p-2">
            <h1 class="display-6 pb-1">Profile</h1>
            <p class="lead">View profile</p>
            @Html.ActionLink("View", "Details", new {id = @Session["doctorAMKA"].ToString()}, new {@class = "btn btn-outline-primary" })
            <p class="lead pt-2">Edit Profile</p>
            @Html.ActionLink("Edit", "Edit", new {id = @Session["doctorAMKA"].ToString()}, new {@class = "btn btn-outline-primary" })
            @* Future delete profile *@
            @* <p class="lead pt-2 text-danger">Delete account</p>
            @Html.ActionLink("Delete", "Delete", new {id = @Session["doctorAMKA"].ToString()}, new {@class = "btn btn-outline-danger" }) *@
        </div>
    </div>
</div><br>